version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      APP_ADMIN_EMAILS: ${APP_ADMIN_EMAILS}
      APP_SHEETS_SPREADSHEET_ID: ${APP_SHEETS_SPREADSHEET_ID}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-pro}
      APP_FRONTEND_ORIGIN: http://localhost:3000
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/service-account.json
    volumes:
      - ./backend/credentials:/app/credentials:ro
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      BACKEND_URL: http://backend:8080
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: promptlab
      POSTGRES_USER: promptlab
      POSTGRES_PASSWORD: promptlab
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - optional
volumes:
  pgdata:
